<a href="https://colab.research.google.com/github/RohanThawait/linear_regression_from_scratch/blob/main/Linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Linear Regression using least squaare solution**
<br>
# X = (A.T@A)(-1)(A.T)Y

In [55]:
import numpy as np
A =np.array([[1,1,1],[1,2,1],[2,3,1]])
y = np.array([3,4,8])
a_t = A.T
c = a_t@A

det_A = np.linalg.det(A)
if det_A != 0:
    print("Matrix is invertible.")
    A_inv = np.linalg.inv(c)
    print("Inverse of matrix A:")
    print(A_inv)
else:
    print("Matrix is singular and cannot be inverted.")

ans = A_inv@a_t
X = ans@y
print()
print(X)

Matrix is invertible.
Inverse of matrix A:
[[ 6.00000000e+00 -3.00000000e+00 -2.00000000e+00]
 [-3.00000000e+00  2.00000000e+00 -0.00000000e+00]
 [-2.00000000e+00 -7.40148683e-17  3.00000000e+00]]

[ 3.  1. -1.]
